influxdata/influxdb-comparisons

cmd/bulk_load_opentsdb/main.go
Added 'values' word to specify that result actually means values rate
=> Improved result print message by specifying unit

cmd/query_benchmarker_influxdb/fasthttp_client.go, cmd/query_benchmarker_influxdb/http_client.go, cmd/query_benchmarker_influxdb/http_client_common.go, cmd/query_benchmarker_influxdb/http_client_pool.go, cmd/query_benchmarker_influxdb/main.go
- fixed default http client for multiple use
- setting idle connection timeout to reasonable value
- avoid using precreated http clients in query_benchmark_influxdb tool because it is useless and not properly done (will deprecate it in some future commit)
=> fixed default http client configuration

cmd/bulk_load_es/main.go, cmd/bulk_load_influx/http_writer.go, cmd/bulk_load_influx/main.go
- ES 6.4. contains preconfigured templates, so no failing in case of finding existing templates
- ES 6.4. requires valid Content-Type header when creating template
- ES:  Printing also response body in case of error
-influx: Failing gracefully, with final finish message
=> Elastic Search fixes for 6.4.3, influx bulk load improvement

bulk_data_gen/devops/devops_net.go
Is this a clerical error?
devlops_net mistakenly used devlops_redis's RedisFields
=> devlops_net mistakenly used devlops_redis's RedisFields

cmd/bulk_load_influx/main.go
Ignore _internal and telegraf dbs when starting up Influx
=> Influxdb has a telegraf db which can be ignored

bulk_data_gen/common/serializer_opentsdb.go
```
before: 61M/s
after:  577M/s
```
test use `./data_gen --format opentsdb --balh balh | pv > /dev/null` with i7-8550U and LPDDR3
=> OpenTSDB serializer speed up

cmd/bulk_load_es/main.go
* `_doc` and `_all` fields are obsolete in ES 7
=> feat: add ES 7 templates

bulk_query/http/common.go, bulk_query/http/fasthttp_client.go, bulk_query/http/http_client.go, bulk_query_gen/influxdb/influx_common.go, bulk_query_gen/influxdb/influx_dashboard_all.go, bulk_query_gen/influxdb/influx_dashboard_availability.go, bulk_query_gen/influxdb/influx_dashboard_cpu_num.go, bulk_query_gen/influxdb/influx_dashboard_cpu_utilization.go, bulk_query_gen/influxdb/influx_dashboard_disk_allocated.go, bulk_query_gen/influxdb/influx_dashboard_disk_usage.go, bulk_query_gen/influxdb/influx_dashboard_disk_utilization.go, bulk_query_gen/influxdb/influx_dashboard_http_request_duration.go, bulk_query_gen/influxdb/influx_dashboard_http_requests.go, bulk_query_gen/influxdb/influx_dashboard_kapa_cpu.go, bulk_query_gen/influxdb/influx_dashboard_kapa_load.go, bulk_query_gen/influxdb/influx_dashboard_kapa_ram.go, bulk_query_gen/influxdb/influx_dashboard_memory_total.go, bulk_query_gen/influxdb/influx_dashboard_memory_utilization.go, bulk_query_gen/influxdb/influx_dashboard_nginx_requests.go, bulk_query_gen/influxdb/influx_dashboard_queue_bytes.go, bulk_query_gen/influxdb/influx_dashboard_redis_memory_utilization.go, bulk_query_gen/influxdb/influx_dashboard_system_load.go, bulk_query_gen/influxdb/influx_dashboard_throughput.go, bulk_query_gen/influxdb/influx_devops_common.go, bulk_query_gen/influxdb/influx_iot_common.go, bulk_query_gen/query.go, cmd/bulk_load_influx/http_writer.go, cmd/bulk_load_influx/main.go, cmd/bulk_query_gen/main.go, cmd/query_benchmarker_influxdb/main.go
This PR adds 2.x OSS support.
Note: Some Flux queries may use obsolete or inefficient code (`bulk_query_gen/influxdb`).
=> feature: add InfluxDB 2.x support

cmd/bulk_load_influx/main.go
Currently the tool throws an exception and quits for 1.x enterprise clusters unless `--do-abort-on-exist=false` is passed, because the tool checks for _any_ existing databases. As far as I can tell, the `_internal` DB is created automatically, and should not count in the check for whether DBs already exist in the cluster
=> fix: the check for existing databases should ignore _internal database

bulk_query/http/fasthttp_client.go, bulk_query/http/http_client.go, bulk_query/query.go, bulk_query/stats.go, cmd/query_benchmarker_influxdb/main.go
These changes move all log messaging for influx query benchmarks to stderr, and add an option to print results as JSON to stdout.
=> Enable option for json output for query benchmarker

bulk_data_gen/common/simulation.go, bulk_query_gen/influxdb/influx_windowagg_common.go, bulk_query_gen/influxdb/influx_windowagg_count.go, bulk_query_gen/influxdb/influx_windowagg_first.go, bulk_query_gen/influxdb/influx_windowagg_last.go, bulk_query_gen/influxdb/influx_windowagg_max.go, bulk_query_gen/influxdb/influx_windowagg_mean.go, bulk_query_gen/influxdb/influx_windowagg_min.go, bulk_query_gen/influxdb/influx_windowagg_sum.go, cmd/bulk_data_gen/main.go, cmd/bulk_query_gen/main.go
The window-aggregate queries use the iot case's data. I've structured the generation so that every aggregate is its own query "type", so each one can be benchmarked and tracked independently. I'm not sure if that's helpful or more complicated than it needs to be; I know the Flux team tracked each aggregate separately, and there have been some single-aggregate bugs in the past.
=> feat: add window aggregate query-gen logic (and alias for data gen)

bulk_data_gen/common/simulation.go, bulk_query_gen/influxdb/influx_bareagg_common.go, bulk_query_gen/influxdb/influx_bareagg_count.go, bulk_query_gen/influxdb/influx_bareagg_first.go, bulk_query_gen/influxdb/influx_bareagg_last.go, bulk_query_gen/influxdb/influx_bareagg_max.go, bulk_query_gen/influxdb/influx_bareagg_mean.go, bulk_query_gen/influxdb/influx_bareagg_min.go, bulk_query_gen/influxdb/influx_bareagg_sum.go, cmd/bulk_data_gen/main.go, cmd/bulk_query_gen/main.go
Part of influxdata/influxdb#22015
Data was reused from #183
Queries were generated using:
```
for format in influx-http influx-flux-http; do
for agg in mean min max first last count sum; do
bulk_query_gen -timestamp-end 2018-01-07T00:00:00Z -use-case bare-agg -format ${format} -query-type ${agg} -query-interval 3h
done
done
```
I ran 1000 test queries per format/agg pair.
| Query format | Min | Mean | Max |
| ---------: | --: | ---: | --: |
| influxql | 1075.375075 | 1840.4832337930022 | 5420.303289 |
| flux | 788.945928 | 977.169301243 | 3265.637433 |
| Query format | Min | Mean | Max |
| ---------: | --: | ---: | --: |
| influxql | 759.275873 | 1347.7069262249995 | 2296.865368 |
| flux | 940.026132 | 1000.4270708260019 | 1121.242632 |
| Query format | Min | Mean | Max |
| ---------: | …
=> feat: add query-gen cases for bare aggregates

cmd/query_benchmarker_influxdb/main.go
Adds a new CLI flag to the `query_benchmarker_influxdb` command `-use-compatibility` that will allow InfluxQL HTTP queries to be used with a 2.x influxd server via the compatibility `/query` API endpoint.
To use this endpoint, DBRPs need to be set up, and a `-token` needs to be provided with the command.
=> feat: allow for running influxql queries with compatbibility API

bulk_query_gen/influxdb/influx_iot_common.go, bulk_query_gen/influxdb/influx_iot_light_level.go, cmd/bulk_query_gen/main.go
Part of https://github.com/influxdata/influxdb/issues/22149
Adds a query to the IoT use case that simply selects the `level` field from the `light_level_room` measurement between an 8-hour time range.
Testing locally with the IoT dataset used by the `influxdb` automated performance tests, the flux version is quite a bit faster, completing in about 7 seconds vs ~15 seconds for influxql.
=> feat: add query for only filtered data for IoT use case

bulk_query_gen/influxdb/influx_iot_common.go, bulk_query_gen/influxdb/influx_iot_light_level.go, cmd/bulk_query_gen/main.go
As a follow-up to https://github.com/influxdata/influxdb-comparisons/pull/188, this removes the `GROUP BY *` statement from the InfluxQL query. This makes the InfluxQL query run a little bit faster, but still slower than the Flux query in my local tests.
Without the `GROUP BY *`, the list of results would look something like this:
```
{
"results": [
{
"statement_id": 0,
"series": [
{
"name": "light_level_room",
"columns": [
"time",
"level"
],
"values": [
[
"2018-01-01T03:12:00Z",
9999.817330076934
],
[
"2018-01-01T03:12:00Z",
10015.688820248402
],
[
"2018-01-01T03:12:00Z",
9983.836965520972
]
}
]
}
]
}
```
With the `GROUP BY *`, the results are grouped like this:
```
{
"results": [
{
"statement_id": 0,
"series": [
{
"name": "light_level_room",
"tags": {
"home_id": "0000000000000", …
```
=> chore: remove `GROUP BY *` from IoT light-level-8-hr

bulk_query_gen/influxdb/influx_iot_aggregate_keep.go, bulk_query_gen/influxdb/influx_iot_common.go
Hopefully fixes an issue pointed out by @danxmoran where a panic was caused by "bad time bounds"
=> chore: fix panic caused by RandWindow in aggregate-keep use-case

bulk_query_gen/influxdb/influx_iot_common.go, bulk_query_gen/influxdb/influx_iot_sorted_pivot.go, cmd/bulk_query_gen/main.go
Perf test for https://github.com/influxdata/influxdb/issues/22016.
The performance data I gathered:
||   max   |   mean  |
|----------------|:-------:|:-------:|
| InfluxQL (1.8) | 4.29ms | 0.26ms |
| Flux (2.x) | 19.39ms | 14.03ms |
This data is not completely fair, since the `pivot()` function does not exist in InfluxQL as stated [here](https://docs.influxdata.com/influxdb/v1.8/flux/flux-vs-influxql/#pivot), but since InfluxQL will pivot automatically, it should still be a valid test.
=> feat: Flux Sorted Pivot perf test

bulk_data_gen/common/simulation.go, bulk_query_gen/influxdb/influx_common.go, bulk_query_gen/influxdb/influx_group_window_transpose_common.go, bulk_query_gen/influxdb/influx_group_window_transpose_count.go, bulk_query_gen/influxdb/influx_group_window_transpose_first.go, bulk_query_gen/influxdb/influx_group_window_transpose_last.go, bulk_query_gen/influxdb/influx_group_window_transpose_max.go, bulk_query_gen/influxdb/influx_group_window_transpose_mean.go, bulk_query_gen/influxdb/influx_group_window_transpose_min.go, bulk_query_gen/influxdb/influx_group_window_transpose_sum.go, cmd/bulk_query_gen/main.go
Part of https://github.com/influxdata/influxdb/issues/22152
This adds query generators for queries involving a `group() |> aggregateWindow()` sequence of functions, or the equivalent InfluxQL query.
There is a (currently disabled via feature-flag) pushdown in OSS for these kinds of queries [here](https://github.com/influxdata/influxdb/blob/8e5a0705a3c14c69ab681268c4d7aecd98204434/query/stdlib/influxdata/influxdb/rules.go#L887-L897). It covers the aggregate functions of `count`, `sum`, `min`, and `max`, and the queries are aligned to the those. `mean`, `first`, and `last` are also included as query types, although these are not applicable to the pushdown.
Enabling that pushdown will cause some queries to be faster, but some to be slower. Queries covering data with high cardinality become …
=> feat: queries for group window

bulk_query_gen/influxdb/influx_iot_battery_voltage.go, bulk_query_gen/influxdb/influx_iot_common.go, cmd/bulk_query_gen/main.go
Part of https://github.com/influxdata/influxdb/issues/22156
This PR adds a query to the IoT queries that queries over multiple measurements with an OR condition in the case of the Flux query.
Flux queries are usually slower than InfluxQL doing this kind of query, depending on the time range covered by the query. If the time range is relatively small compared to the total time range in which data exists, the flux queries will be significantly slower, presumably due to [this code](https://github.com/influxdata/influxdb/blob/master/v1/services/storage/series_cursor.go#L97) requiring a full block scan to determine the results for flux. As the time range of the query approaches the full range in which data exists, the gap closes and flux actually becomes faster than InfluxQL once the query …
=> feat: add iot query for multiple measurements with OR

bulk_query_gen/influxdb/influx_iot_common.go
Fixes an issue in the flux query for `iot` `aggregate-keep` not being in quotations, causing the query to fail
=> chore: fix filter not being formatted correctly in `aggregate-keep`

cmd/bulk_query_gen/main.go
This adds the ability to generate queries for a few query types in the IoT use case with alternate names that will be more descriptive as to the shape of the query for our automated performance benchmarks.
Since some of these queries were created specifically for the performance benchmarks, a follow-up PR will remove the query types that are being aliased off of to clean things up after the automated perf tests have switched to the new names.
The mapping is as follows:
- `1-home-12-hours`: `fast-query-small-data`
- `battery-levels`: `multi-measurement-or`
- `light-level-8-hr`: `standalone-filter`
=> feat: add aliases to describe query ops for IoT use case

bulk_query_gen/influxdb/influx_iot_aggregate_drop.go, bulk_query_gen/influxdb/influx_iot_aggregate_keep.go, bulk_query_gen/influxdb/influx_iot_common.go, cmd/bulk_query_gen/main.go
`drop` is the mirror to `keep`. I suspect that `keep` will be easier to optimize than `drop` (in the same way that our `group` pushdown works for `mode: by` and not `mode: except`), so it'd be good to track both separately.
=> feat: add iot query case for aggregate-drop

bulk_data_gen/common/simulation.go, cmd/bulk_query_gen/main.go
Related to https://github.com/influxdata/influxdb/issues/22350
This provides aliases that can be used to generate queries for group-window queries based on a use-case, rather than the use case of `group-window-transpose` with different types yielding the high or low cardinality versions of the queries.
The reasoning for this may seem opaque currently, but this should help make the logic for https://github.com/influxdata/influxdb/pull/22480 much simpler, and allow for the high and low cardinality versions of the queries to be created for the correct time range.
The existing use-case is not being removed at this time, so this is purely an additive change and will not break any existing behaviors.
=> chore: add aliases for group window based on cardinality on use case

bulk_data_gen/common/simulation.go, cmd/bulk_query_gen/main.go
Closes #203
Removes the now unused alias for `group-window-transpose`, since the full `group-window-transpose-high-card` & `group-window-transpose-low-card` are being used instead.
=> chore: delete unused group-window-transpose code

bulk_query_gen/influxdb/influx_bareagg_common.go
Closes https://github.com/influxdata/influxdb-comparisons/issues/206
Related to https://github.com/influxdata/influxdb/issues/22467
Updates the InfluxQL version of the query to output equivalent results as the flux queries for bare aggregates.
Example of current flux query:
```javascript
from(bucket:"benchmark_db") 
|> range(start:2018-01-01T01:00:00Z, stop:2018-01-01T03:00:00Z) 
|> filter(fn:(r) => r._measurement == "air_condition_room" and r._field == "temperature") 
|> last() 
|> yield()
```
Output:
```
,result,table,_start,_stop,_time,_value,_field,_measurement,home_id,room_id,sensor_id
,_result,0,2018-01-01T01:00:00Z,2018-01-01T03:00:00Z,2018-01-01T02:59:00Z,15,temperature,air_condition_room,0000000000000,1,0000000000005
,_result,1,2018-01-01T01:00:00Z,2018-01-01T03:00:00Z,2018-01-01T …
```
=> fix: influxql bare aggs work like flux

bulk_data_gen/common/simulation.go, bulk_query_gen/influxdb/influx_ungroupedagg_common.go, bulk_query_gen/influxdb/influx_ungroupedagg_count.go, bulk_query_gen/influxdb/influx_ungroupedagg_first.go, bulk_query_gen/influxdb/influx_ungroupedagg_last.go, bulk_query_gen/influxdb/influx_ungroupedagg_max.go, bulk_query_gen/influxdb/influx_ungroupedagg_mean.go, bulk_query_gen/influxdb/influx_ungroupedagg_min.go, bulk_query_gen/influxdb/influx_ungroupedagg_sum.go, cmd/bulk_data_gen/main.go, cmd/bulk_query_gen/main.go
After #207, we're missing a test for aggregates over the entirety of a dataset (ungrouped & un-windowed). In OSS using `group()` causes the group-aggregate pushdown to be triggered, but I think within the pushdown logic it ends up using a different iterator/cursor than you'd get with `group(columns: ["foo", "bar"])`.
=> feat: add query-gen cases for "ungrouped" aggregates

bulk_data_gen/common/serializer_mongodb.go, bulk_query_gen/cassandra/cassandra_iot_common.go, bulk_query_gen/influxdb/influx_iot_common.go, bulk_query_gen/mongodb/mongo_devops_common.go, bulk_query_gen/mongodb/mongo_iot_common.go, bulk_query_gen/mongodb/options.go, bulk_query_gen/timescaledb/timescale_iot_common.go, cmd/bulk_load_mongo/main.go, cmd/bulk_query_gen/main.go
This PR adds support for "schema" where measurements are stored in separate collections by type (eg. cpu, network). It is default behavior.
Also fixes `1-home-12-hours` _iot_ query duration to match the query name.
=> fix: MongoDB schema and iot use-case
